######################################################################
# @author      : lyz
# @file        : Makefile
# @created     : Thursday May 23, 2024 14:57:58 CST
######################################################################

run: hello
	java hello

hello: hello.java
	javac hello.java

clean:
	rm -rf *.class
