######################################################################
# @author      : lyz (lyz@$HOSTNAME)
# @file        : Makefile
# @created     : Tuesday Nov 12, 2024 14:53:34 CST
######################################################################

main: main.rs
	rustc main.rs

.PHONY: clean

run: main
	./main

clean:
	rm -f main
