hw05: hw05.hs
	ghc hw05.hs -main-is hw05

run:
	./hw05

down:
	wget http://www.seas.upenn.edu/~cis194/extras/05-IO/clues.zip
	unzip clues.zip
	wget http://www.seas.upenn.edu/~cis194/extras/05-IO/Parser.hs

doc:
	wget http://www.seas.upenn.edu/~cis194/hw/05-IO.pdf

clean:
	rm -rf victims.json new-transaction.json *.hi *.o hw05
