res:
	wget https://pdos.csail.mit.edu/6.828/2016/lec/l-overview.md
	wget https://pdos.csail.mit.edu/6.828/2016/lec/l-overview/redirect.c
	wget https://pdos.csail.mit.edu/6.828/2016/homework/sh.c
xv6:
	git clone git://github.com/mit-pdos/xv6-public.git
gdbinit:
	ln -s $(HOME)/.gdbinit $(pwd)/gdbinit
jos:
	git clone https://pdos.csail.mit.edu/6.828/2016/jos.git lab
