ALGS4JAR="/home/liuyang/.local/jar/algs4.jar"

PercolationStats.class: PercolationStats.java
	javac -classpath $(ALGS4JAR) PercolationStats.java

Percolation.class: Percolation.java
	javac -classpath $(ALGS4JAR) Percolation.java

run:
	java PercolationStats

clean:
	rm -rf *.class
